name: Tests CI

on:
  pull_request:
    branches: [development, master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm build --if-present
    - run: npm test

